name: 'Test & Deploy Backend' 

on:
  push:
    branches:
      - back-dev
  pull_request:
    branches:
      - back-dev
      
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.17.0
    
    - name: Install NPM packages
      run: npm ci
    
    - name: Run tests
      run: npm run test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Build, Push and Deploy to Heroku # set whatever name you want to this step
        id: heroku
        uses: jctaveras/heroku-deploy@v1.0.0 # use the latest version of the action
        with:
          email: ${{ secrets.HEROKU_EMAIL }} 
          api_key: ${{ secrets.HEROKU_API_KEY }} 
          app_name: ${{ secrets.HEROKU_APP_NAME }} 
          dockerfile_path: './digital-wallet-backend' 
          process_type: 'web' 
